<?php
$mandatory = [
    'TRANSACTIONID',
    'INCOMINGOROUTGOINGFLAG',
    'PARTYCUSTOMERID',
    'PARTYACCOUNTNUMBER',
    'COUNTERPARTYVIRTUALACCOUNTNUMBER',
    'COUNTERPARTYACCOUNTCOUNTRY',
    'TRANSACTIONDATETIME',
    'TRANSACTIONAMOUNT',
    'TRANSACTIONTYPE',
    'TRANSACTIONCATEGORY',
    'CHANNELCODE',
    'BILLERID',
    'INTERNATIONALINDICATOR',
    'ONUSFLAG',
    'USERID',
    'RESPONSECODE',
    // 'ERRORCODE',
    'SESSIONID',
    'LANGUAGECODE',
    'AUTHID',
];

$default_mapping = [
    'INCOMINGOROUTGOINGFLAG' => 'D',
    'COUNTERPARTYACCOUNTCOUNTRY' => 'ID',
    'TRANSACTIONCATEGORY' => 'Virtual Account Transfer',
    'CHANNELCODE' => 'IBR',
    'INTERNATIONALINDICATOR' => 'D',
    'ONUSFLAG' => 'OnUs',
];

$default_mapping_keys = array_keys($default_mapping);

$q_where_tran_id_unmatch = "TRANSACTIONID != CONCAT('IBR', REPLACE(REPLACE(REPLACE(TRANSACTIONDATETIME, ':', ''), '-', ''),' ', ''), PARTYCUSTOMERID)";
$q_where_tran_id_match = "TRANSACTIONID = CONCAT('IBR', REPLACE(REPLACE(REPLACE(TRANSACTIONDATETIME, ':', ''), '-', ''),' ', ''), PARTYCUSTOMERID)";